name: stock
source:
  type: parquet
  path: data.parquet
description: dataset-description
columns:
- name: SECURITY_INNER_CODE
  type: integer
- name: SECURITY_CODE
  type: integer
- name: SECUCODE
  type: string
- name: TRADE_DATE
  type: string
- name: SECURITY_NAME_ABBR
  type: string
- name: SUPERDEAL_INFLOW
  type: integer
- name: SUPERDEAL_OUTFLOW
  type: integer
- name: PRIME_INFLOW
  type: integer
- name: CLOSE_PRICE
  type: string
- name: CHANGE_RATE
  type: string
- name: TRADE_MARKET_CODE
  type: integer
- name: TURNOVERRATE
  type: float
- name: PRIME_COST
  type: float
- name: PE_DYNAMIC
  type: float
- name: PRIME_COST_20DAYS
  type: float
- name: PRIME_COST_60DAYS
  type: float
- name: ORG_PARTICIPATE
  type: float
- name: PARTICIPATE_TYPE
  type: integer
- name: BIGDEAL_INFLOW
  type: integer
- name: BIGDEAL_OUTFLOW
  type: integer
- name: BUY_SUPERDEAL_RATIO
  type: float
- name: BUY_BIGDEAL_RATIO
  type: float
- name: RATIO
  type: float
- name: RATIO_3DAYS
  type: float
- name: RATIO_50DAYS
  type: float
- name: TOTALSCORE
  type: float
- name: RANK_UP
  type: integer
- name: RANK
  type: integer
- name: FOCUS
  type: float
- name: SECURITY_TYPE_CODE
  type: integer
